### ISSUE TITLE
Provide easy access to `CraftError` -> message

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-cli#119]
Developing an application with `craft-cli`, I'd like to write a test which asserts that `CraftError` was raised with a specific message.

Currently, `message`, which gets passed in in `__init__.py`, is not directly exposed via `CraftError`.

I only see two ways to access the message, and both are not ideal:

- via `repr` of the exception instance -> not viable due to escaping special chars, e.g.
```
'CommandError("Requested input from \'build\', but more than one job with that name was previously executed and produced output artifacts in the following paths: [PosixPath(\'/tmp/tmpsje0degh/build/1\'), PosixPath(\'/tmp/tmpsje0degh/build/0\')].")'
```
- via `.args` -> feels not really right, and maybe you'll change order at some point, so my code would break
```
("Requested input from 'build', but more than one job with that name was previously executed and produced output artifacts in the following paths: [PosixPath('/tmp/tmpsje0degh/build/1'), PosixPath('/tmp/tmpsje0degh/build/0')].",)
```

Is there a better way? If not, could you please expose `message` directly?

**Comment by facundobatista** [comment]
Hello! Thanks for the question.

Why not doing `str()` of the exception? that will give you the message...

**Comment by jugmac00** [comment]
Oh wow :-) Thanks. Exactly what I was looking for.
