### ISSUE TITLE
Support "streaming" INFO log messages in BRIEF mode

### ISSUE THREAD

**Issue by tigarmo** [canonical/craft-cli#165]
### What needs to get done

Add a new behavior (enable-able at init()) to the emitter where log messages of level `INFO` or more are "streamed" in a single line between `permanent=True` messages when in BRIEF mode

### Why it needs to get done

The idea is to give the user _some_ sense of what's happening even in BRIEF mode, without overwhelming them with too many messages with "irrelevant" (that is, too low-level) info.

**Comment by sergiusens** [comment]
Info and higher
