### ISSUE TITLE
Documentation on Read the Docs is outdated

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-cli#50]
Unfortunately, the new documentation (#49) has not landed on rtd yet, see https://craft-cli.readthedocs.io/en/latest/

![Screenshot from 2022-01-18 21-28-28](https://user-images.githubusercontent.com/9895620/150013635-217616a5-1ddf-4f37-b5f0-7435e07c6a52.png)

Interestingly, on https://readthedocs.org/projects/craft-cli/builds/ the last failed build is older than a month.

P.S.: Documentation cannot be built locally as `tox` is broken, see #47

**Comment by sergiusens** [comment]
Thanks for the heads up...
![image](https://user-images.githubusercontent.com/1146853/150124062-a3244281-640c-40d1-ab34-06985d25e934.png)
