### ISSUE TITLE
Allow emitter to be paused

### ISSUE THREAD

**Issue by cmatsuoka** [canonical/craft-cli#67]
There are situations where we may allow a process to execute with complex terminal output. A typical example would be a craft tool re-execution inside a build provider, which would use craft-cli to report the execution progress. In this case, we don't want the spinner from the outer instance to appear during the execution of the inner instance, which can have its own spinner. A possible implementation could be a context manager that pauses the emitter.

**Comment by facundobatista** [comment]
Pausing the emitter has a real benefit of allowing the subprocess to take control of the screen. 

However I don't know if we currently need this. The spinner does not appear anymore in the subprocess (fixed a while ago to not show it if there is no TTY) and the solution to not show the timestamps is already requested in #61.

**Comment by cmatsuoka** [comment]
Snapcraft currently needs this functionality. See the screen output in snapcore/snapcraft#3660, emitter output from the emitter instance launcher clashes with the emitter progress report from snapcraft running inside the instance.
